#define FAConstructor_VERSION_MAJOR "1"
#define FAConstructor_VERSION_MINOR "7"
#define FAConstructor_VERSION_PATCH "0"
#define CMAKE_CXX_COMPILER "/usr/bin/g++"
#define CMAKE_CXX_COMPILER_VERSION "7.4.0"
#define FAConstructor_WITH_OMP "ON"
#define FAConstructor_RELEASE_TYPE "Release"
